---
galaxy_info:
  role_name: ssh_hardening
  author: Michiel Van Herreweghe
  description: OpenSSH hardening (port, ciphers, AllowUsers, banner)
  license: MIT
  min_ansible_version: "2.14"
  platforms: []

dependencies: []
